# Generated by Django 5.2.7 on 2025-10-31 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('diretor', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('ano_lancamento', models.PositiveIntegerField()),
                ('duracao', models.PositiveIntegerField()),
                ('sinopse', models.TextField(blank=True)),
            ],
        ),
    ]
